{
 "title": "DCGM1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Power Usage - time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Power usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU Util - time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}